TRAIN:
  ENABLE: True
  DATASET: Amarv
  BATCH_SIZE: 16
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: False
  MIXED_PRECISION: True
DATA:
  PATH_TO_DATA_DIR: "$AMARV_ANNS"
  PATH_PREFIX: "$AMARV_RUN2"
  PATH_LABEL_SEPARATOR: ","
  PATH_CACHE: True
  SPEED_CORRECTION: True
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [1]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  MODALITY: Depth
  MAX_DEPTH: 1.0
  MIN_DEPTH: 0.0
  MEAN: [0.12872302532196045]
  STD: [0.03646882623434067]
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 5.0
  LR_POLICY: cosine
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  ARCH: omnivore
  FP16_ALLREDUCE: True
  NUM_CLASSES: 272
  MODEL_NAME: OmnivoreDepth
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
  OMNIVORE_FROZEN_STAGE: 0
TEST:
  ENABLE: True
  DATASET: AMARV
  BATCH_SIZE: 32
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
  ACCEPT_MISSING: True
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
